
const sampleData = {
  products: [
    {
      sku:"3216544565",
      name: "Polo Sporting Stretch Shirt",
      slug: "polo-sporting-stretch-shirt",
      category: "fashion",
      description: "Classic Polo style with modern comfort",
      images: [
        "/images/sample-products/p1-1.jpg",
        "/images/sample-products/p1-2.jpg",
      ],
      regularPrice: "10",
      brand: "Polo",
      rating: 4.5,
      numReviews: 10,
      stock: 5,
      isFeatured: true,
      banner: "banner-1.jpg",
      deliveryType: "EXP",
    },
    {
      sku:"65454343345",
      name: "Brooks Brothers Long Sleeved Shirt new text to see the overflow effect",
      slug: "brooks-brothers-long-sleeved-shirt",
      category: "fashion",
      description: "Timeless style and premium comfort",
      images: [
        "/images/sample-products/p2-1.jpg",
        "/images/sample-products/p2-2.jpg",
      ],
      regularPrice: "10.50",
      discountedPrice: "8.50",
      brand: "Brooks Brothers",
      rating: 4.2,
      numReviews: 8,
      stock: 10,
      isFeatured: true,
      banner: "banner-2.jpg",
      deliveryType: "EXP",
    },
    {
      sku:"001115554586",
      name: "Tommy Hilfiger Classic Fit Dress Shirt",
      slug: "tommy-hilfiger-classic-fit-dress-shirt",
      category: "Men's Dress Shirts",
      description: "A perfect blend of sophistication and comfort",
      images: [
        "/images/sample-products/p3-1.jpg",
        "/images/sample-products/p3-2.jpg",
      ],
      regularPrice: "12.25",
      brand: "Tommy Hilfiger",
      rating: 4.9,
      numReviews: 3,
      stock: 0,
      isFeatured: false,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"45979878788",
      name: "Calvin Klein Slim Fit Stretch Shirt",
      slug: "calvin-klein-slim-fit-stretch-shirt",
      category: "Men's Dress Shirts",
      description: "Streamlined design with flexible stretch fabric",
      images: [
        "/images/sample-products/p4-1.jpg",
        "/images/sample-products/p4-2.jpg",
      ],
      regularPrice: "55.75",
      discountedPrice: "49.75",
      brand: "Calvin Klein",
      rating: 3.6,
      numReviews: 5,
      stock: 10,
      isFeatured: false,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"450001111222",
      name: "Polo Classic Pink Hoodie",
      slug: "polo-classic-pink-hoodie",
      category: "Men's Sweatshirts",
      description: "Soft, stylish, and perfect for laid-back days",
      images: [
        "/images/sample-products/p6-1.jpg",
        "/images/sample-products/p6-2.jpg",
      ],
      regularPrice: "99.75",
      brand: "Polo",
      rating: 4.6,
      numReviews: 12,
      stock: 8,
      isFeatured: true,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"45988877555",
      name: "Polo Ralph Lauren Oxford Shirt",
      slug: "polo-ralph-lauren-oxford-shirt",
      category: "Men's Dress Shirts",
      description: "Iconic Polo design with refined oxford fabric",
      images: [
        "/images/sample-products/p5-1.jpg",
        "/images/sample-products/p5-2.jpg",
      ],
      regularPrice: "10",
      brand: "Polo",
      rating: 4.7,
      numReviews: 18,
      stock: 6,
      isFeatured: false,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"4563000545",
      name: "Apple iPhone 16 Pro 256GB Natural Titanium",
      slug: "iphone-16-pro-max",
      category: "Mobile-Phones",
      description: "Latest iPhone with advanced features",
      images: ["/images/sample-products/iphone16promax.jpg"],
      regularPrice: "4199.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 12,
      stock: 2,
      isFeatured: true,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"45634235422",
      name: "Apple Iphone 13 (4GB RAM, 256GB)",
      slug: "apple-iphone-13",
      category: "Mobile-Phones",
      description: "Latest iPhone with advanced features and great camera",
      images: ["/images/sample-products/iphone13.jpg"],
      regularPrice: "1699.00",
      brand: "apple",
      rating: 3.7,
      numReviews: 12,
      stock: 5,
      isFeatured: true,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"45634234232",
      name: "Apple Watch Series 7",
      slug: "apple-watch-series-7",
      category: "apple smart watches",
      description: "Latest Apple Watch with advanced health features",
      images: ["/images/sample-products/appleWatch.jpg"],
      regularPrice: "4299.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 12,
      stock: 2,
      isFeatured: true,
      banner: null,
      deliveryType: "EXP",
    },
    {
      sku:"45634234562",
      name: "Apple Macbook Pro 2017",
      slug: "apple-macbook-pro",
      category: "macbooks",
      description: "Latest Apple macbook with advanced health features",
      images: ["/images/sample-products/macbookPro.jpg"],
      regularPrice: "8199.00",
      brand: "apple",
      rating: 4.7,
      numReviews: 0,
      stock: 1,
      isFeatured: true,
      banner: null,
      deliveryType: "EXP",
    },
  ],
};

export default sampleData;
